services:
  dbt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dbt-athena
    environment:
      - AWS_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - ../dbt_project:/dbt
      - ~/.aws:/root/.aws:ro
    working_dir: /dbt
    entrypoint: ["tail", "-f", "/dev/null"]
    networks:
      - dbt-net

networks:
  dbt-net:
    driver: bridge